import type { Facility, Pipeline } from '@/types';

export const mockFacilities: Facility[] = [
  {
    id: 'FAC-001',
    name: 'Houston Refinery Complex',
    type: 'refinery',
    status: 'active',
    coordinates: { lat: 29.7604, lng: -95.3698 },
    capacity: 250000,
    lastInspection: '2024-01-15',
    operator: 'PetroTech Industries',
    region: 'Gulf Coast',
    description: 'description',
  },
  {
    id: 'FAC-002',
    name: 'Eagle Ford Drilling Site Alpha',
    type: 'drilling_rig',
    status: 'active',
    coordinates: { lat: 28.9783, lng: -97.8963 },
    lastInspection: '2024-02-01',
    operator: 'Lone Star Energy',
    region: 'South Texas',
    description: 'description',
  },
  {
    id: 'FAC-003',
    name: 'Cushing Storage Terminal',
    type: 'storage_tank',
    status: 'active',
    coordinates: { lat: 35.9856, lng: -96.7664 },
    capacity: 500000,
    lastInspection: '2024-01-28',
    operator: 'Midwest Storage LLC',
    region: 'Oklahoma',
    description: 'description',
  },
  {
    id: 'FAC-004',
    name: 'Bakken Processing Plant',
    type: 'processing_plant',
    status: 'maintenance',
    coordinates: { lat: 47.7511, lng: -101.7777 },
    capacity: 150000,
    lastInspection: '2024-02-10',
    operator: 'Northern Energy Corp',
    region: 'North Dakota',
    description: 'description',
  },
  {
    id: 'FAC-005',
    name: 'Permian Pump Station 7',
    type: 'pump_station',
    status: 'active',
    coordinates: { lat: 31.8457, lng: -102.3676 },
    lastInspection: '2024-01-20',
    operator: 'West Texas Pipeline',
    region: 'Permian Basin',
    description: 'description',
  },
  {
    id: 'FAC-006',
    name: 'Port Harcourt Refinery',
    type: 'refinery',
    status: 'active',
    coordinates: { lat: 4.8156, lng: 7.0498 }, // Port Harcourt
    capacity: 250000,
    lastInspection: '2024-01-15',
    operator: 'NNPC Limited',
    region: 'Niger Delta',
    description: 'description',
  },
  {
    id: 'FAC-007',
    name: 'Agbami Offshore Platform',
    type: 'drilling_rig',
    status: 'active',
    coordinates: { lat: 4.1833, lng: 5.3167 }, // Off Bayelsa coast
    lastInspection: '2024-02-01',
    operator: 'Chevron Nigeria',
    region: 'Gulf of Guinea',
    description: 'description',
  },
  {
    id: 'FAC-008',
    name: 'Bonny Crude Terminal',
    type: 'storage_tank',
    status: 'active',
    coordinates: { lat: 4.4516, lng: 7.1707 }, // Bonny Island
    capacity: 500000,
    lastInspection: '2024-01-28',
    operator: 'Shell Nigeria',
    region: 'Rivers State',
    description: 'description',
  },
  {
    id: 'FAC-009',
    name: 'Lagos Gas Processing Plant',
    type: 'processing_plant',
    status: 'maintenance',
    coordinates: { lat: 6.5244, lng: 3.3792 }, // Lagos
    capacity: 150000,
    lastInspection: '2024-02-10',
    operator: 'TotalEnergies Nigeria',
    region: 'Southwest',
    description: 'description',
  },
  {
    id: 'FAC-010',
    name: 'Escravos Pump Station',
    type: 'pump_station',
    status: 'active',
    coordinates: { lat: 5.5667, lng: 5.0 }, // Escravos
    lastInspection: '2024-01-20',
    operator: 'Agip Nigeria',
    region: 'Delta State',
    description: 'description',
  },
];

export const mockPipelines: Pipeline[] = [
  {
    id: 'PIP-001',
    name: 'Gulf Coast Mainline',
    type: 'crude_oil',
    status: 'active',
    coordinates: [
      { lat: 29.7604, lng: -95.3698 },
      { lat: 30.2672, lng: -97.7431 },
      { lat: 31.7619, lng: -106.485 },
    ],
    diameter: 36,
    length: 850,
    pressure: 1200,
    lastInspection: '2024-01-10',
    operator: 'PetroTech Industries',
    region: 'Gulf Coast',
    material: 'Material',
    description: 'description',
  },
  {
    id: 'PIP-002',
    name: 'Eagle Ford Gathering System',
    type: 'crude_oil',
    status: 'active',
    coordinates: [
      { lat: 28.9783, lng: -97.8963 },
      { lat: 29.4241, lng: -98.4936 },
      { lat: 29.7604, lng: -95.3698 },
    ],
    diameter: 24,
    length: 320,
    pressure: 800,
    lastInspection: '2024-02-05',
    operator: 'Lone Star Energy',
    region: 'South Texas',
    material: 'Material',
    description: 'description',
  },
  {
    id: 'PIP-003',
    name: 'Cushing Distribution Network',
    type: 'refined_products',
    status: 'active',
    coordinates: [
      { lat: 35.9856, lng: -96.7664 },
      { lat: 36.154, lng: -95.9928 },
      { lat: 39.0458, lng: -94.5795 },
    ],
    diameter: 30,
    length: 450,
    pressure: 1000,
    lastInspection: '2024-01-25',
    operator: 'Midwest Storage LLC',
    region: 'Oklahoma',
    material: 'Material',
    description: 'description',
  },
  {
    id: 'PIP-004',
    name: 'Niger Delta Mainline',
    type: 'crude_oil',
    status: 'active',
    coordinates: [
      { lat: 4.8156, lng: 7.0498 }, // Port Harcourt
      { lat: 5.5167, lng: 5.75 }, // Warri
      { lat: 6.3432, lng: 5.625 }, // Benin
    ],
    diameter: 36,
    length: 850,
    pressure: 1200,
    lastInspection: '2024-01-10',
    operator: 'NNPC Limited',
    region: 'Niger Delta',
    material: 'Material',
    description: 'description',
  },
  {
    id: 'PIP-005',
    name: 'Offshore Gathering System',
    type: 'crude_oil',
    status: 'active',
    coordinates: [
      { lat: 4.1833, lng: 5.3167 }, // Agbami Field
      { lat: 4.4516, lng: 7.1707 }, // Bonny Terminal
      { lat: 4.8156, lng: 7.0498 }, // Port Harcourt
    ],
    diameter: 24,
    length: 320,
    pressure: 800,
    lastInspection: '2024-02-05',
    operator: 'Chevron Nigeria',
    region: 'Gulf of Guinea',
    material: 'Material',
    description: 'description',
  },
  {
    id: 'PIP-006',
    name: 'West African Gas Pipeline',
    type: 'refined_products',
    status: 'active',
    coordinates: [
      { lat: 6.5244, lng: 3.3792 }, // Lagos
      { lat: 6.3167, lng: 5.6167 }, // Ore
      { lat: 6.13, lng: 1.2225 }, // Lomé (Togo)
    ],
    diameter: 30,
    length: 450,
    pressure: 1000,
    lastInspection: '2024-01-25',
    operator: 'West African Gas Pipeline Company',
    region: 'West Africa',
    material: 'Material',
    description: 'description',
  },
];
